### ISSUE TITLE
Time zones appear twice in post date

### ISSUE THREAD

**Issue by ctanas** [spaghettiwews/hugonews#2]
Any idea why? 

My website, where this happens, is here: https://retroburn.space/ and its repo is here: https://github.com/ctanas/retroburn

**Comment by spaghettiwews** [comment]
That second UTC time offset (+0200) is ideally supposed to be a [time zone abbreviation](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations), in your case EET I guess... 
Check how it renders when you build the site locally on your computer.. It might be an issue with the environment where the website is being built, i.e. netlify?

**Comment by spaghettiwews** [comment]
Also, yesterday, just before you opened the issue, I had changed the [date/time from a timestamp to a relative age](https://github.com/spaghettiwews/hugonews/commit/342b6a47f09e345f1b9ed429ef73368d1719ab93) - although (now that i think of it) that will require the website to be rebuilt at least daily to keep the ages up-to-date.

**Comment by ctanas** [comment]
I was going to ask how could I enable relative age timestamp! Thanks for your replies, they cleared the issue..
